version: "3.7"
services:
    app:
        build:
            args:
                user: maftuna
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: todo
        container_name: todo-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - todo
    db:
        image: mysql:5.7
        container_name: todo-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: 'todo_app'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - todo
        ports:
            - "4306:3306"
    nginx:
        image: nginx:1.17-alpine
        container_name: todo-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - todo

networks:
  todo:
    driver: bridge
